# -*- coding: utf-8 -*-
"""RewardPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqmqvXvKpAZe7hP4DUiz0RHw2eUuaeSE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

df=pd.read_csv("train_data.csv")
print(df);

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('timestamp(seconds)')
plt.ylabel('blockreward(ether)')
plt.scatter(df.timestamp,df.blockReward,color="red", marker=".")

model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(df.timestamp.values.reshape(-1,1), df.blockReward.values.ravel())

new_timestamp=np.array([[1686644543]])
predicted_blockReward=model.predict(new_timestamp);
plt.scatter(df.timestamp,df.blockReward,label='Data Points')
plt.scatter(new_timestamp,predicted_blockReward,color="red", label='Predicted Future Block Reward')
plt.xlabel('timestamp(seconds)')
plt.ylabel('blockreward(ether)')
plt.legend();
plt.show();

print("Predicted Block Reward", predicted_blockReward[0]);